### ISSUE TITLE
Can I specify a default indexing strategy?

### ISSUE THREAD

**Issue by KevinBongart** [toptal/chewy#167]
Hi, thanks for this great gem!

We're having a few questions over here, mainly about how to constantly update an index after creating, saving and updating records. Our goal is to import all records once, then always use the sidekiq strategy for new or updated records.

Wrapping the `#save` and `#<<` and `#create` and `#update` calls with a `Chewy.strategy(:sidekiq)` block seems very cumbersome considering we're dealing with a lot of STI models who each redefine these methods.

Is there a way to use something like `after_commit :reindex`?

Thanks

**Comment by pyromaniac** [comment]
Hey! Could you plead read https://github.com/toptal/chewy#index-definition, section 5 carefully? `update_index` statement does exactly the thing you need.

**Comment by alekseychaikovsky** [comment]
Hi, thanks again for the gem. `update_index` is perfect and we have that on the superclass, however the issue is that we have many many STI models that subclass this, and they are created and updated in many different places in the codebase. Instead of wrapping each case of this in a `Chewy.strategy(:sidekiq)` I am wondering if there is a way to set a default strategy for `update_index` ?

**Comment by pyromaniac** [comment]
By default controller actions are wrapped with `:atomic` strategy, but there is an option to change this (https://github.com/toptal/chewy#rails-application-strategies-integration, https://github.com/toptal/chewy/blob/master/lib/chewy/config.rb#L32 wow, I have broken docs here), Other places, say, rake tasks, have to be wrapped manually

**Comment by pyromaniac** [comment]
You see, this is a design question, `:atomic` and `:sidekiq` strategies are doing reindex when block is evaluated completely, this is about performance, say, you can update your model 100 times in block, but id would be still updated only once. This is really matters when you have branchy hmt associations and you are updating a couple of root objects, but this causes update of almost all associated objects, you can check this by wrapping any place with `urgent` strategy and benchmarking it. So, this strategies just can't be set globally because the update will never happen.

On other hand if you are sure that you don't have branchy association and this would not affect your performance, you can try to experiment with `around_commit { |block| Chewy.strategy(:urgent, &block) }` Not sure about syntax. Also I've just thought that if this will work, `:atomic` and `:sidekiq` would work here as well, and this will be a little bit more effective. Also maybe you have to add some `Thread.current` option to be able to disable this callback and set this option in controllers and other places where you want to use strategy manually.

But I personally would prefer just to set strategy blocks just wherever I need. This would be much more readable and understandable.
