### ISSUE TITLE
Support for CompletionSuggester?

### ISSUE THREAD

**Issue by fullofcaffeine** [toptal/chewy#210]
Howdy Arkadiy!

I'm using Chewy with a Rails app and need to implement a SQL LIKEish auto-completion feature. I've posted on StackOverflow about the issues I'm having with ES when right now, more details @: http://stackoverflow.com/questions/31173988/emulate-a-sql-like-search-with-elasticsearch.

Someone suggested me to use the CompetionSuggestion type (pun not intended). How would I use it from Chewy? Any hints?

Cheers man!

**Comment by pyromaniac** [comment]
So, I've read about CompetionSuggestion. It should be simple to use in chewy:
```
field :suggest, type: 'completion', value: -> { {input: [first_name, last_name], output: full_name, payload: {object_id: id}} }
```

I have to try it also :) But I've never used it before. Instead I was using special analyzer on text field:

```
settings analysis: {
    analyzer: {
      autocomplete_term: {
        tokenizer: 'autocomplete_edge',
        filter: %w[lowercase icu_folding]
      },
      autocomplete_search: {
        tokenizer: 'keyword',
        filter: %w[lowercase icu_folding]
      }
    },
    tokenizer: {
      autocomplete_edge: {
        type: 'nGram',
        min_gram: 1,
        max_gram: 100
      }
    }
  }
```

And use then `autocomplete_term` in mapping on desired fields and `autocomplete_search` analyzer in search queries:

```
MyIndex.query(multi_match: {
      query: term,
      analyzer: 'autocomplete_search',
      fields: %w[first_name, last_name]
    })
```

Also `autocomplete_search` might be put in mapping as `search_analyzer` as well, so you would not have to specify in explicitly in query.

This approach is fast enough and works exactly like SQL LIKE. But the native one seems to be much more interesting, probably they might be even combined since is is possible to specify analyzers in `completion` field mapping

**Comment by fullofcaffeine** [comment]
@pyromaniac Thanks so much for your help! I already made it to work, and in fact, without using `CompletionSuggester`, as per the selected answer in this stackoverflow post: http://stackoverflow.com/questions/31173988/emulate-a-sql-like-search-with-elasticsearch..

Thanks again, and keep up the great work with Chewy. I'm currently using it myself and loving it (again).

Cheers!
