### ISSUE TITLE
define_type with time-dependent ActiveRecord scope

### ISSUE THREAD

**Issue by kenzan100** [toptal/chewy#359]
I'm writing this to make sure if this is an intended effect :smiley: 

suppose you have a AR model with scope like
`scope :published, -> { where("articles.published_at <= ?", DateTime.now) }`

and with Chewy mapper

```
class ArticlesIndex < Chewy::Index
  define_type Article.published do
    # all the mappings
  end
end
```

and this won't give you a fresh `published` scope when invoking `update_index` in the AR model.

I solved it with using `delete_if` proc, but if you'd like me to submit a PR reminding this behaviour on README, I'm more than happy to do so :hand: 

Thanks so much for proving such a handy gem to Ruby btw :smiley_cat:

**Comment by pyromaniac** [comment]
I've got the same conversation today already: https://github.com/toptal/chewy/issues/326#issuecomment-203389199 

Since you both clearly seems to be in collusion, I have to think about all this stuff, but I'm still not sure that this is the thing you need. It probably will cause unpredictable side-effects in future. I personally would prefer to index everything and then filter on querying instead.

**Comment by pyromaniac** [comment]
Oh, btw, you are still able to calculate time.now in sql instead of ruby

**Comment by kenzan100** [comment]
I'm still new to Elasticsearch (newbies will look for high-level wrapper like this), so thank you for the suggestions!

I'll consider them (and probably stick to Elasticsearch friendly way).
