### ISSUE TITLE
Custom nested objects with field definitions for dynamic fields

### ISSUE THREAD

**Issue by leoc** [toptal/chewy#729]
Hello there,

I am having a dynamic set of customizable fields per my document model and would like to make them searchable and sortable.

```ruby
class CustomField < AR::Model
  has_many :custom_values
  # t.column :key, :jsonb
  # t.column :value_type, :string
end

class CustomValue < AR::Model
  belongs_to :custom_field

  # column :value, :jsonb

  def key; custom_field.key; end
  def value_type; custom_field.value_type; end
end

class Document < AR::Model
  update_index('documents#document')
  # t.column :name, :string

  has_many :custom_values
end
```

For that I would like to have an index like so:

```ruby
class DocumentsIndex < Chewy::Index
  field :name
  field :fields, type: 'object', value: ->(document){ document.custom_values.map { |cv| [cv.key, cv] }.to_h } do
    field :key, type: 'keyword'
    field :value
    field :value_type
  end
end
```

Is that possible? 

The goal is to filter the custom field values properly via simple query strings and filter terms, but also sort the result by a specific custom field via `order('fields.my_custom_field_key.value')`. What kind of drawbacks would I have? I am currently having custom fields of type `string`, `integer`, `float`, `boolean` and `date`. I see that it would be nice to filter date fields with date-related search queries (`"gte" : "now-1d/d", "lt" :  "now/d"`).

I'm grateful for every hint! Maybe this is an interesting, not so unusual usecase! :-)

![](https://media4.giphy.com/media/3oEjHWXddcCOGZNmFO/giphy.gif)

Cheers :beers:

**Comment by dalthon** [comment]
Hi @leoc, I am not sure if I understood you well, but I believe you can achieve what you want simply having your mapping like this:

```ruby
class DocumentsIndex < Chewy::Index
  field :name
  field :fields, type: 'object'
end
```

Because if you don't define the type of object, you still are able to query those because every time ES finds a new object key it figures out value type and define its mapping accordingly.

The only caveat that you will need to worry about is that once you add a given key with some value, every value must match the same type by key, otherwise you will not be able to import this entry.

**Comment by leoc** [comment]
Hi @dalthon, thanks a lot for the reply. The caveat you mentioned is exactly what I worry about. For instance if the value of a custom date field is empty and I add a new document with a date value for that, then I get errors about missing values or type mismatches. Also sorting did cause errors, if I remember correctly.  I wondered whether it would be possible to define the "schema" for the `type: 'object'`-field...

I hope this explains my issue a little. At the moment I am very busy, but I will try to create a little test script to reproduce the issues I had.

**Comment by dalthon** [comment]
@leoc Sorry I missed your quick reply and noticed almost one year after while doing a housekeeping here.

But now re-reading your first message and second I got a better grasp of the issue here.

What you ask will not work because ElasticSearch itself does not support it. Every nested field must have the same value matched by key regardless of other sibling fields.

Also chewy would have some trouble defining what you want, because new fields would be added in runtime, and chewy does not define mappings in runtime, but defines them separately by its rake task.

One solution that could work for you would be something like:

```ruby
class DocumentsIndex < Chewy::Index
  field :name
  field :fields, type: 'object' do
    field :name
    field :type
    field :integer_value
    field :term_value
    field :keyword_value
    # ... and so on ...
  end
end
```

So for each type you add a key named like `TYPE_value` and then your data should follow that example:

```ruby
{
  name: 'some number',
  type: 'integer',
  integer_value: 123
}
```
