### ISSUE TITLE
Question: Multi-model indices why removed?

### ISSUE THREAD

**Issue by johnbeynon** [toptal/chewy#767]
I'm curious why multi model indices were removed? There are examples in the comments of the code it seems for multiple `define_type` in the index definitions but you get the error `Multiple types are deprecated` if you try and use them?

What the suggestion for searching across multiple models these days?

Thanks!

**Comment by rabotyaga** [comment]
Hey @johnbeynon !
They are removed because Elasticsearch removed mapping types starting from version 6, take a look: https://www.elastic.co/guide/en/elasticsearch/reference/6.8/removal-of-types.html, https://www.elastic.co/blog/moving-from-types-to-typeless-apis-in-elasticsearch-7-0.
You can use queries to multiple indexes instead: https://github.com/toptal/chewy/pull/657
